### PR TITLE
Postgresql updates

### PR DESCRIPTION
**Pull request by theharq**
#### What this PR does:

This PR removes references of mysql.
#### Notes

Maybe I'm missing something but I don't see why we need to support 2 types of db at the same time.. this is realm of activerecord, rails can switch changing only the driver gem and the database.yml for development.

### CODE REVIEW

**Comment by matthewford** [comment]
@theharq because otherwise we will have to fork signon - we currently have a PR to maintain both dbs, we will use postgresql they will continue to use MySQL till they are ready to migrate.

**Comment by matthewford** [comment]
https://github.com/alphagov/signonotron2/pull/467

**Comment by theharq** [comment]
I see, makes sense to help with the transition, thank you for the clarification :smiley:

**Comment by matthewford** [comment]
can open a new pr for that .cfignore commit though

**Pull request closed without merging**
